### ISSUE TITLE
CRAN update

### ISSUE THREAD

**Issue by oganm** [pridiltal/staplr#10]
It seems like a reasonable time has passed since the initial upload to CRAN. Since there are backwards incompatible changes in this version, it might make sense to have it out in the earliest opportunity. Are there things left to do before the next CRAN release?

Edit: I have also been holding out on adding staplr to [shinyapps-package-dependencies](https://github.com/rstudio/shinyapps-package-dependencies) because I'm lazy and didn't want to go back to fix the tests after the update but will do so after the release

**Comment by pridiltal** [comment]
Good idea. Just submitted to CRAN. fingers crossed.

**Comment by pridiltal** [comment]
On CRAN now: [https://cran.r-project.org/web/packages/staplr/](https://cran.r-project.org/web/packages/staplr/)  🎉

**Comment by oganm** [comment]
https://github.com/rstudio/shinyapps-package-dependencies/pull/145

**Comment by oganm** [comment]
So... I may have screwed up a little and introduced a bug that snuck into the latest update. The CRAN version does not allow numeric inputs to the two `rotate_` functions and only accepts character inputs (for the rotation angles), which is not the documented usage. I have now fixed it to accept both numeric and character inputs here but the damage is done I'm afraid. There are now unit tests for most functionality so stuff like that shouldn't happen hopefully.

**Comment by pridiltal** [comment]
Thank you very much. This is now fixed in v2.2.0.

**Comment by oganm** [comment]
shinyapps people seem to be sleeping. closing the issue as that's mostly a waiting game now.
