### ISSUE TITLE
`staplr`  hex stickers

### ISSUE THREAD

**Issue by pridiltal** [pridiltal/staplr#15]
`staplr` checked in to useR! 2018 in Brisbane, Australia

![img_1591](https://user-images.githubusercontent.com/20311818/42607754-d957919c-85c7-11e8-8986-ffc3b551ee57.jpg)

![img_1618](https://user-images.githubusercontent.com/20311818/42607769-ee84f136-85c7-11e8-9e1f-f3049b643389.jpg)

@oganm @padpadpadpad @mathesong

**Comment by oganm** [comment]
Whoa fancy
