### ISSUE TITLE
staplr's set_fields and get_fields running for hours with no results

### ISSUE THREAD

**Issue by laresbernardo** [pridiltal/staplr#17]
Hey guys. Great library.. just what I need right now. The thing is that I'm having problems with the basic example, using the included PDF when installed. I'm running:
```
library(staplr)
pdfFile = system.file('testForm.pdf', package = 'staplr')
fields <- get_fields(pdfFile)
fields$TextField1$value <- "Test"
set_fields(input_filepath = pdfFile,
           output_filepath = 'filledPdf.pdf', 
           fields = fields)
```
And after hours.. still waiting. 

On the other hand, I tried with a personal PDF I have, with lots of filling spaces, and same result.. I import the PDF correctly and when running the `get_fields` function, nothing happens for hours. Note that it works with the previous code.

Hope you can help me solve this issue!

Thanks, B.

**Comment by laresbernardo** [comment]
This is the PDF if you want to try the `get_fields` and/or `set_fields` with any values: [Dropbox Link](https://www.dropbox.com/s/etaj1vmgxi94jg5/colpatria.pdf?dl=0)

**Comment by oganm** [comment]
The link seems to be dead. Could you send it again? 

You can attach the pdf to a github comment

**Comment by laresbernardo** [comment]
Better: [colpatria.pdf](https://github.com/pridiltal/staplr/files/2288605/colpatria.pdf)

**Comment by oganm** [comment]
So to be clear, using the test form also causes the same issue and neither works after hanging for a few hours?

- Are you on a mac, if so have you seen this from readme?
> NB: pdftk is known to hang indefinitely on macOS High Sierra. If this
happens to you, [this
version](https://www.pdflabs.com/tools/pdftk-the-pdf-toolkit/pdftk_server-2.02-mac_osx-10.11-setup.pkg)
should work for macOS El Capitan (10.11), it also works on Sierra
(10.12) and High Sierra (10.13).

- Does any other function from the package work or is it specific to get/set_fields?

**Comment by laresbernardo** [comment]
Super. I actually am working on a mac with High Sierra and following your readme instructions managed to solve the issue. Thanks and glad you already knew the answer ;)
Keep it up!!!

**Comment by laresbernardo** [comment]
Another small issue Im having now is, for the same `colpatria.pdf` shared above, if you go to the section named "1. Solicitud productos de crédito", the VEHICULO and MOTO boxes are not detected by the `get_fields` function. But, if you open it, actually it is well formatted and when clicked it marks a check.

**Comment by laresbernardo** [comment]
And last, but no least: how should we deal with special characters?
For example, if the PDF had the field LINEA, it brings it as L&#205;NEA and then when trying to write the PDF it doesn't know where to insert the value. Is there a way to set UTF-8 or something similar?
Tried with the following to correct those symbols but didn't work:
```
fields <- get_fields(pdfFile)
cols <- data.frame(names = names(fields))
dict <- data.frame(
  symbol = c("&#193;","&#205;","&#201;","&#211;","&#243;","&#209;","&#218;","&#220;"),
  mutation = c("Á","Í","É","Ó","ó","Ñ","Ú","Ü")
)
for (i in 1:nrow(dict)) {
  cols$names <- sub(dict$symbol[i], dict$mutation[i], cols$names)  
}
names(fields) <- cols$names
```

**Comment by oganm** [comment]
Vehiculo and moto boxes are actually there. They are the same object. See VEHICULO (108th element).

About encoding, I am currently unsure. It seems like pdftk's `dump_data_fields` which is used by `get_fields`, replaces special characters with decimal codes while `generate_fdf` used by `set_fields` doesn't, causing the issue. As it stands there isn't a built in work around. 

Do names appear weirdly in the output of `get_fields` function for you as well? For instance I see "`L&#205;NEA`" as the name of the LÍNEA field. If this is what's happening in your system too, that's a good sign as I just need to encode the output of `get_fields` somehow. Will let you know when I have something working

For now, you can manually change the names of those fields in the output of `get_fields`

**Comment by laresbernardo** [comment]
Hey @oganm thanks for your super fast replies. 
Yes, I am also receiving those values in that format but, using the dictionary I shared with you above, it doesn't write those values in the PDF. So I see it as it should be but when running the `set_fields` it doesn't work at all and those spaces remain blank.
About vehiculos you are absolutely right.. there it is! But, País de nacimiento is nowhere and when using the Ciudad de nacimiento, the function actually fills País de nacimiento in the PDF.

**Comment by oganm** [comment]
Are you talking about VEHICULO or LÍNEA? VEHICULO works fine for me. For reference see code below

```r
fields = get_fields('colpatria.pdf')
fields$VEHICULO$value = 1 # to mark VEHICULO
set_fields(input_filepath = 'colpatria.pdf',
           output_filepath = 'filledPdf.pdf', 
           fields = fields)
fields$VEHICULO$value = 2 # to mark MOTO
set_fields(input_filepath = 'colpatria.pdf',
           output_filepath = 'filledPdf2.pdf', 
           fields = fields)
```

Fields with special characters need work on my part. My attempt to manually rename the fields also failed because readLines also fails to read the fdf files properly by default. If you have power to edit the pdfs field names that could be a temporary solution

I don't have time to fix it right now but I'll try to get back to it as soon as possible. Sorry for the inconvenience.

**Comment by laresbernardo** [comment]
Don't worry @oganm you've done a great work!
And yes, I found the VEHICULO value now, super. The one that is nowhere is CIUDAD DE NACIMIENTO. And when setting a value to PAÍS DE NACIMIENTO, it is inserted into the CIUDAD DE NACIMIENTO place. Weird!

**Comment by oganm** [comment]
The field names do not have to be identical to what's written next to them. The producer of the PDF can name a given field whatever they want so some experimentation might be needed before getting things right. Some pdf viewers show the name of the field when you mouse over it (I believe acrobat doesn't, I use pdf xchange viewer but that's for windows). There are [other ways](https://superuser.com/questions/137227/how-to-view-form-field-names-in-a-pdf-document/) to get field names  but not quite practical

**Comment by oganm** [comment]
I just pushed a fix for this. You can get it by

```r
devtools::install_github('pridiltal/staplr')
```

Hopefully it'll work in your machine too

**Comment by laresbernardo** [comment]
Worked perfectly @oganm Thanks!!! 👍 
That was even faster than expected.. thanks again!!
