### ISSUE TITLE
Merge Not working

### ISSUE THREAD

**Issue by ghost** [pridiltal/staplr#18]
Hi, 

Thank you for this package, I have a bunch of pdf files to merge, N = 1,900. I do not have access to any merging software for MS Word or PDF documents. 

I installed the free version of the PDF toolkit, and ran the example of the staple_pdf() below take from the documentation: 
```
library(staplr)
library(lattice)

staple_pdf()
## End(Not run)
## Not run:
dir <- '//user/location'
require(lattice)
for(i in 1:3) {
  pdf(file.path(dir, paste("plot", i, ".pdf", sep = "")))
  print(xyplot(iris[,1] ~ iris[,i], data = iris))
  dev.off()
}
output_file <- file.path(dir, paste('_Full_pdf.pdf', ))
staple_pdf(input_directory = NULL, input_files = NULL,
           output_filepath = NULL)
```
This example creates three pdf files successfully: plots1, plots2, plots3 and is supposed to merge those files into a _full_pdf.pdf file. However, all I get is the prompt window to choose the folder, but no output is generated. 

Please advise, thank you!

**Comment by oganm** [comment]
Why did you set the inputs for the `staple_pdf` to `NULL`? That'll cause you to be prompted to select them using the UI. It should work if you either do select them using the UI or set them to what you want in code.

What you want is

```r
staple_pdf(input_files = file.path(dir, paste("plot", 1:3, ".pdf", sep = "")),
           output_filepath = output_file)
```

Also if you are executing that code from the very beginning, you seem to have a stray `staple_pdf()` which will also cause you to be prompted to provide inputs

**Comment by ghost** [comment]
Awesome I got it to repsond, but no I get this : 
unhandled java exception in main()
java.io.IOException: GetFullPathNameFailed

**Comment by oganm** [comment]
Just to clarify. Do you get an error when you run the code below, unmodified?

```r
dir <- tempfile()
dir.create(dir)
require(lattice)
for(i in 1:3) {
  pdf(file.path(dir, paste("plot", i, ".pdf", sep = "")))
  print(xyplot(iris[,1] ~ iris[,i], data = iris))
  dev.off()
}
output_file <- file.path(dir, paste('Full_pdf.pdf',  sep = ""))
staple_pdf(input_directory = dir, output_filepath = output_file)
staple_pdf(input_files = file.path(dir, paste("plot", 1:3, ".pdf", sep = "")), output_filepath = output_file)
```

If not, that means everything is working fine and we have a problem with the usage. If you send me the code you used, I can point out what went wrong

If the error is still there, then it looks like a problem with the pdftk installation. Do any other functions from the package work? Also, just to be clear, you installed the [pdftk server](https://www.pdflabs.com/tools/pdftk-server/) right? Not the GUI based PDFTK-free. I imagine the GUI version wouldn't be adding a pdftk command to the path but I have no way to know right now

**Comment by ghost** [comment]
Alrighty, so. 

I am running Windows 7. Installed PDFTK server. 

Open RStudio, new session. Ran this exact code.
```r
library(lattice)
library(staplr)

dir <- tempfile()
dir.create(dir)
require(lattice)
for(i in 1:3) {
  pdf(file.path(dir, paste("plot", i, ".pdf", sep = "")))
  print(xyplot(iris[,1] ~ iris[,i], data = iris))
  dev.off()
}
output_file <- file.path(dir, paste('Full_pdf.pdf',  sep = ""))
staple_pdf(input_directory = dir, output_filepath = output_file)
staple_pdf(input_files = file.path(dir, paste("plot", 1:3, ".pdf", sep = "")), output_filepath = output_file)

dir
output_file
```
Got this output: 
```
library(lattice)
library(staplr)
dir <- tempfile()
 dir.create(dir) 
require(lattice)
for(i in 1:3) {pdf(file.path(dir, paste("plot", i, ".pdf", sep = "")))
  print(xyplot(iris[,1] ~ iris[,i], data = iris)) dev.off() }
output_file <- file.path(dir, paste('Full_pdf.pdf',  sep = ""))
staple_pdf(input_directory = dir, output_filepath = output_file)
Unhandled Java Exception in main():
java.io.IOException: GetFullPathName failed
   <<No stacktrace available>>

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
staple_pdf(input_files = file.path(dir, paste("plot", 1:3, ".pdf", sep = "")), output_filepath = output_file)
Unhandled Java Exception in main():
java.io.IOException: GetFullPathName failed
   <<No stacktrace available>>

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
 dir
[1] C:\\Users\\rsanchez\\AppData\\Local\\Temp\\RtmpMBvIpQ\\file62644c6f6c3d
output_file
[1] C:\\Users\\rsanchez\\AppData\\Local\\Temp\\RtmpMBvIpQ\\file62644c6f6c3d/Full_pdf.pdf
```
Some questions: 
After installing PDTFK do i need to do anything else?
Are the path of the files suppose to be like that?

Thanks!

**Comment by ghost** [comment]
Note that when I can open: C:\Users\rsanchez\AppData\Local\Temp\RtmpMBvIpQ\file62644c6f6c3d

but not the way the console presents it with double \ , it is not showing in the comments properly.

only the plot1, plot2, plot3 files are there

**Comment by oganm** [comment]
The file paths look fine that shouldn't be the issue. You could try using pdftk from the command line to see if it actually works. If not working, you probably want to contact pdftk support.
