### ISSUE TITLE
fields filled with set_fields sometimes is not visible initially (a minor edit to the field makes the entire text visible)

### ISSUE THREAD

**Issue by oganm** [pridiltal/staplr#19]
As revealed by #17, pdftk seems to be having problems with writing foreign language characters. 

Problems are:

- `dump_data_fields`'s output encodes special characters in numeric character reference decimals. [Stackoverflow](https://stackoverflow.com/questions/51850775/how-to-decode-a-character-with-numeric-character-references-in-it/51850941#51850941) told me that I can remedy this fairly easily, though it is somewhat hacky.
- `generate_fdf`'s output encodes things correctly but using readLines causes them to be read in hex representations. This can be fixed by changing encoding but I am unsure if it'll happen in all systems. I don't have a good way of testing things in different language devices. This could be fixed by changing the encoding while using `readLines` or writing a similar function to convert hex values into proper characters after using `readLines`

This is the 4th piece of code I wrote that was later revealed to be secretly racist. Need to have a decent way to test things in different localisations. Not sure what the best practices are

**Comment by laresbernardo** [comment]
Hello @oganm it's me again!
I'd like to reopen this ticket because I am experiencing the following issue: when I run the `set_fields` function to fill my PDF, these characters are omitted and added as spaces instead: Ñ, ñ, É, Í, Ó, and maybe some other I haven't catched yet.
Hope you know a fix for this too, thanks!

**Comment by oganm** [comment]
Ah this is what I was afraid of. I cannot replicate this on my side which means it's a system specific problem now.

Below is a slightly modified version of set_fields function. It'll generate one of the intermediate files in your working directory instead of as a temporary file. Below that I added a few lines to run it on our test PDF. could you run this and send me the resulting `newfdf.fdf` and `newFDF.rds` files that should pop up in your working directory?

```r
set_fields = function(input_filepath = NULL, output_filepath = NULL, fields){
  assertthat::assert_that(is.list(fields))
  
  if(is.null(input_filepath)){
    #Choose the pdf file interactively
    input_filepath <- file.choose(new = FALSE)
  }
  if(is.null(output_filepath)){
    #Choose output file interactively
    output_filepath <-  tcltk::tclvalue(tcltk::tkgetSaveFile(filetypes = '{Pdf {.pdf}}'))
  }
  
  tempFDF <- tempfile()
  # create the fdf file to fill
  system_command <- paste('pdftk',
                          shQuote(input_filepath),
                          'generate_fdf','output',
                          shQuote(tempFDF))
  system(system_command)
  
  
  fdf <- paste(readLines(tempFDF,encoding ='latin1'),
               collapse= '\n')
  
  
  for(i in seq_along(fields)){
    fieldToFill <- fields[[i]]
    fdf <- staplr:::fdfEdit(fieldToFill,fdf)
  }
  
  newFDF <- 'newfdf.fdf'
  saveRDS(fdf,'newFDF.rds')
  f = file(newFDF,open = "w",encoding = 'latin1')
  writeLines(fdf, f,useBytes = TRUE)
  close(f)
  
  system_command <- paste('pdftk',
                          shQuote(input_filepath),
                          'fill_form', shQuote(newFDF),
                          'output', shQuote(output_filepath))
  system(system_command)
}

fields <- get_fields(pdfFile)
pdfFile <- system.file('testForm.pdf',package = 'staplr')
fields$TextField1$value = 'bad characters Ñ, ñ, É, Í, Ó'
set_fields(input_filepath = pdfFile,
           output_filepath = 'filledPdf.pdf', 
           fields = fields)

```

**Comment by laresbernardo** [comment]
Thanks for your super fast reply @oganm as always! 👍 

You omitted this line after the `pdfFile` row (instead of after):
`fields <- get_fields(pdfFile)`

I see those characters are well written in the PDF generated now! [filledPdf.pdf](https://github.com/pridiltal/staplr/files/2319964/filledPdf.pdf)

Sadly github doesn't support `.fdf` nor `.rds` files but I think they won't be needed if the PDF generated is correct, right?

**Comment by oganm** [comment]
whops. sorry for the missing line.

so now, we have this example file that works fine in your machine and mine, and your personal file that doesn't. which is partially good because it means this is not necessarily a system dependent issue. but it is also problematic as it means I have no idea what is happening. (the pasted function's code is identical to set_fields from within the package other than those file writing bits so that shouldn't have solved your problem entirely)

when you try the pasted function with your own file, does it work? 

If it does, that means something funny is going on with the package installation. I had experience with some non-ascii characters getting wrongly encoded during package installation process which may cause the same function to behave differently within a package and outside of it. In this case I don't see what might be causing it though, the functions themselves don't have non ascii characters in them.

**Comment by laresbernardo** [comment]
Ok, so I tried that function outside the library and am having the same result, other than the two additional created files. Still having spaces instead of the original characters when the PDF is created.
Any further ideas to check? You can try with this file.. insert something like `ñÑéÉÓü` and see what happens: [filled_fields.pdf](https://github.com/pridiltal/staplr/files/2320024/filled_fields.pdf)
Btw, that file is filled with the library's tags for each field as I showed you before ;)

**Comment by laresbernardo** [comment]
Hello guys. Any idea on how to fix this yet?
Thanks!

**Comment by oganm** [comment]
Didn't have time to take a look yet. Will do so as soon as possible

**Comment by laresbernardo** [comment]
Sure @oganm don't worry! Just let us know when you have 👍 
Thanks for your time

**Comment by oganm** [comment]
I am still stuck on this one. The intermediate files before getting into pdftk seems just fine. The failure happens when pdftk's `fill_form` command is executed. ~~pdftk is closed source~~ and even if it was open I haven't touched java in 7 years.

Sent a mail to pdftk's developer about this. Hopefully he'll know something.

**Comment by oganm** [comment]
relabelled the issue since all encoding issues  (so far) have been fixed but this remains to be an issue. It is a PDF specific and pdftk related issue which limits what we can do about it. One thing to look at is the difference between the pdf binaries when the text written is visible and invisible and see what it corresponds to based on the pdf format specification. That could be something we can manually fiddle with.

**Comment by oganm** [comment]
need_appearances option seems to fix this issue...
