### ISSUE TITLE
Argument is of length zero when running set_fields

### ISSUE THREAD

**Issue by laresbernardo** [pridiltal/staplr#20]
Is there any way to detect which field is the one problematic one?
I'm getting the following error message when running the final `set_fields` function:
```
Error in if (fieldToFill$type %in% c("Text", "Choice")) { : 
  argument is of length zero
```
I am working with 177 fields and don't know which one is causing this problem.
Thanks and hope you can give me an idea or add a message with a suggested field!!

**Comment by oganm** [comment]
Could you send me the file? As far as I know, fields should always have a type. 

Will also look into adding error messages

**Temporary measure:** Failure seems to be happening because on the fields is missing it's type. You can find out which and remove it by doing

```r
fields %>%
    purrr::map('type') %>%
    purrr::map_int(length) %>%
    {which(.==0)}
```

**Comment by oganm** [comment]
@laresbernardo I was wondering if the file that caused this issue had field names that were separated by `.`s. I came across an example of a field name without types when dealing with these field names. staplr can now correctly deal with such files. If I can verify your issue appeared in a file like that I'll close this issue as well.

**Comment by gfleetwood** [comment]
@oganm Hello. I'm running into this issue, and none of the suggested solutions worked for me.

**Comment by oganm** [comment]
If you sent me a file with the issue I can take a look

**Comment by gfleetwood** [comment]
@oganm Is there a way I can send it to you privately?

**Comment by oganm** [comment]
Sure sure, can just send it to ogan.mancarci@gmail.com

**Comment by oganm** [comment]
Using the file you sent I was able to do

```{r}
library(staplr)
fields = get_fields('received_file.pdf')
fields$last_name$value = 'Mancarci'

set_fields('received_file.pdf','output.pdf',fields)
```

Repeating this causes the issue for you? If so could you send me the output of

```r
staplr:::pdftk_cmd()
```

**Comment by gfleetwood** [comment]
@oganm I don't get an issue with that code.

**Comment by oganm** [comment]
Ah so it was a syntax issue or is something still wrong?

**Comment by gfleetwood** [comment]
@oganm I suppose it's a problem on my end then. I'm using multiple inputs to set the values for the form:

```
    fields = get_fields(pdfFile)
    
    for(name in names(fields)) {
      fields[[name]][['value']] = input[[name]]
    }
    
    set_fields(pdfFile, NULL, fields)
```

But running the code above the length of all the inputs is 1.

**Comment by oganm** [comment]
I suspect what is happening here is that the `input` object does not contain an entry for every `field`. If that is the case,  looping over the names in `input` instead should fix it

```r
fields = get_fields(pdfFile)

for(name in names(input)) {
      fields[[name]][['value']] = input[[name]]
}
set_fields(pdfFile, NULL, fields)
```
This happens because setting a list component of an R list to NULL simply erases it instead of setting it to NULL.

otherwise we are probably failing to parse one of the inputs in which case it'd be really helpful to know which one

**Comment by gfleetwood** [comment]
@oganm I used your code - looping through names(input) - and now I'm getting this error:

```
Warning: Error in fdfEdit: Field "" could not be found in the pdf. You may be using the wrong fields object or forgot to set convert_field_names correctly.
```

I'm going to stop here since I rewrote my code in PyShiny, and I'm getting no issues there with the package I'm using.  Thanks for the help,

**Comment by oganm** [comment]
Great and no worries! 

That seems to suggest you have a `""` as a name in the `input` object. I'd have to know how it got there but the execution should have succeeded despite the warning as it'll just be ignored
