### ISSUE TITLE
Check which field fills which field on PDF

### ISSUE THREAD

**Issue by laresbernardo** [pridiltal/staplr#22]
Hello.
I've been using this awesome library for filling PDFs but I got a terrible experience filling and guessing which fields were which. I wrote the following script to create a filled with features names a PDF so you can see which names the library assigned to each blank.
Hope it comes useful for all of you. Thanks to @oganm for this super tool!
```
# FILL ALL FEATURES WITH FEATURES NAMES ON NEW PDF
library(dplyr)
library(staplr)
buttons <- names(fields)[sapply(seq_along(fields), function(x){"Button" %in% fields[[x]]})]
all <- data.frame(names = names(fields)) %>% 
  mutate(buttons = ifelse(names %in% buttons, TRUE, FALSE))
for (i in 1:nrow(all)) {
  if (all$buttons[i] == TRUE) {
    fields[[all$names[i]]]$value <- 1
  } else {
    fields[[all$names[i]]]$value <- all$names[i] 
  }
}
set_fields(pdfFile,"filled_fields.pdf", fields)
```

**Comment by oganm** [comment]
Edited your post for a quick fix

I'm only responsible for the form filling bits. But thanks :tada:. Rest is @pridiltal and others.

Getting the names could indeed be annoying. I am yet to find a robust solution to that especially for buttons. I might incorporate a version of your code into the package.

I am also considering to hack something in that'll give the page number which should at least narrow the search space. Do you think it would help if the output of set_fields had an option to return page numbers?

Any idea what happened with the typeless field at #20 by the way?

**Comment by laresbernardo** [comment]
Super! That would be great @oganm 
I guess having the page number could help too. Personally, the PDF I'm working with right now has about 200 fields but almost everything is in the first one. It's a quite annoying file! This library will make my life so much easier when all is set :)

**Comment by oganm** [comment]
By the way, if you ever get your hands on a Windows machine, [PDF exchange viewer](https://www.tracker-software.com/product/pdf-xchange-viewer/download?fileid=448) shows you the field names when you mouse over them
