### ISSUE TITLE
rotate_pdf doesn't actually turn pages by given degrees

### ISSUE THREAD

**Issue by oganm** [pridiltal/staplr#28]
When testing something else I noticed that the way we describe rotations and the way staplr interprets is a little different if we do `rotate_pdf`  with `page_rotation = 90` you'll get something like

```
|--------|
| text   |
|        |
|        |
|        |    
|        |
|        |
|--------|

           ↓  90 (east) rotation

|------------------|
|                t |
|                e |
|                x |
|                t |
|------------------|
```

Imagine the letters of the text rotated as well. This is expected behaviour. However if you take that output and try to rotate again you get

```
|------------------|
|                t |
|                e |
|                x |
|                t |
|------------------|

           ↓  90 (east) rotation

|------------------|
|                t |
|                e |
|                x |
|                t |
|------------------|
```
This happens because `pdftk` doesn't actually try to rotate the pages if they already have the right orientation. In this context, `east` doesn't mean "turn this file by 90 degrees" but "turn it so the top of the file is on the right side". 

This behaviour was unexpected for me. We should either try to make sure to clarify this on docs or find a way to get the current orientation of the page and tell pdftk to rotate relative to the current orientation. Accepting the pdtfk notation (north east south west) could also help in clarifying what the function is actually doing

**Comment by pridiltal** [comment]
Glad  you spot this.  This should be clarified and documented properly
