### ISSUE TITLE
pre-cran

### ISSUE THREAD

**Issue by oganm** [pridiltal/staplr#32]
@pridiltal If you didn't send it to cran yet could you wait for the weekend. there is a small change i want to make about encoding problems

**Comment by pridiltal** [comment]
@oganm I submitted it today :rocket: . Let me know when you are happy to go for a patch release or minor release.

**Comment by pridiltal** [comment]
version 2.9.0 now on [CRAN](https://cran.r-project.org/web/packages/staplr/index.html) :anchor:

**Comment by oganm** [comment]
bittersweet yay. will push the change when I can, then we can update on cran when it's appropriate.
