### ISSUE TITLE
get_fields() hangs for pdf I created, works for package example file

### ISSUE THREAD

**Issue by jzadra** [pridiltal/staplr#34]
Following the example code, `get_fields()` works fine:

``` r
require(staplr)
#> Loading required package: staplr
pdfFile <- system.file('testForm.pdf',package = 'staplr')

fields <- get_fields(pdfFile)
fields
#> $TextField1
#> $TextField1$type
#> [1] "Text"
#> 
#> $TextField1$name
#> [1] "TextField1"
#> 
#> $TextField1$value
#> [1] "Jone was here"
# .... (more deleted for brevity)
```

However, when I try the same code with a fillable PDF I've created, `get_fields()` hangs:

[Test 2.pdf](https://github.com/pridiltal/staplr/files/3074334/Test.2.pdf)

```
pdf <- "~/temp/Test 2.pdf"
fields <- get_fields(pdf)

```

I am using:
OSX Mojave (10.14.3),
XQuartz 2.7.11 
staplr 2.9.0
pdftk 2.02

**Comment by jzadra** [comment]
Solved with using the pdftk version for OSX High Sierra.  Perhaps update the readme to unclude all OSX versions above El Cap?  It doesnt' currently list Mojave.

**Comment by oganm** [comment]
This has been a recurring issue. Wonder if it may be possible to catch hanging sessions to return a warning. I don't have access to a mac so this is hard to deal with for me. If anyone does and time to play around with this it would be appreciated

**Comment by oganm** [comment]
No longer needed with pdftk-java
