### ISSUE TITLE
Switch to pdftk-Java and ship a prebuilt jar

### ISSUE THREAD

**Issue by oganm** [pridiltal/staplr#42]
I just learned that a [pure Java](https://gitlab.com/pdftk-java/pdftk) implementation of pdftk exists. If we committed to using this version:

- users wouldn't have to follow an external link to install pdftk on their systems
- Mac users who follow a wrong link wouldn't get stuck
- cran can properly run our tests
- this version is in active development which means there are real people that we can talk to when things go wrong

All that will be needed is to place the jar in `inst`, direct mentions of pdftk to this file, and make sure everything still works. Cran wants Java programs to be compiled into jars anyway so that doesn't leave much for us to do. 

Some caveats:
- ~~we may have change licenses. Pdftk-Java is on gpl2 which based on my understanding is not compatible with gpl3~~.
- running jars require finding JAVA_HOME which is often problematic in different systems. I have some heuristics that I use for my own packages and rjava has more advanced ways of locating Java but problems can still arise especially when multiple versions of Java is installed (eg 32 vs 64 bit). This one doesn't seem to pick between 32 vs 64 bit Java so rjava should be good enough. Worth to do some tests though. 
- we may have to fiddle with Java options. Most operations shouldn't be too memory intensive but for extreme use cases, problems can arise with default settings. This also requires some testing. Though if this was going to be an issue, I suspect we would see it with regular pdftk as well 

Edit: Also original pdftk won't be available in later ubuntu version due to a dependency of it going away so at least a part of the userbase will be using pdftk-java whether we wan't it or not

**Comment by Bisaloo** [comment]
Obligatory I am not a lawyer disclaimer but my understanding is that `pdftk-java` is GPLv2+, which is compatible with GPLv3:

>  This program is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, **or
    (at your option) any later version.**

https://gitlab.com/pdftk-java/pdftk/blob/aac5d907b275f8ddfd6cd2599908fe7b5d41489a/LICENSE#L296-299

**Comment by oganm** [comment]
This interpretation does appear to be correct

**Comment by oganm** [comment]
A working version that uses pdftk-java is currently at https://github.com/pridiltal/staplr/tree/java
