### ISSUE TITLE
Cran removal

### ISSUE THREAD

**Issue by oganm** [pridiltal/staplr#43]
Seems like the package is gone.

**Comment by pridiltal** [comment]
Hi @oganm  what made you say that?

**Comment by oganm** [comment]
oh nevermind... I could not get in for some time. And neither could [this service](https://cranalerts.com/) I use to get notified when changes happen because it send me a mail saying it was removed. I don't know if it was the entire cran or just staplr but all is well now.

**Comment by oganm** [comment]
It was @daattali's fault

https://twitter.com/daattali/status/1143931756464279552

**Comment by daattali** [comment]
I shift the blame to https://www.r-project.org/ and all its services being down! (But I will also fix the bug in cranalerts)
