### ISSUE TITLE
staple_pdf example not working on Windows PC

### ISSUE THREAD

**Issue by RichardMeyer-Eppler** [pridiltal/staplr#45]
The example for staple_pdf included in the package is not working for me.

The three plot PDFs get written to the tempdir successfully, in my case: "C:\\Users\\Richard\\AppData\\Local\\Temp\\Rtmp6TqGpZ"

The generated output_file path is:
"C:\\Users\\Richard\\AppData\\Local\\Temp\\Rtmp6TqGpZ/Full_pdf.pdf"

However, when running 
`staple_pdf(input_directory = dir, output_filepath = output_file)`

I only get the integer `127` as a result, with no error messages. I have tried manually changing the ouput_file path, as well as supplying a vector of input files, all with `127` as a result.

Any ideas?

`sessionInfo()`

R version 3.6.1 (2019-07-05)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18362)

Matrix products: default

locale:
[1] LC_COLLATE=German_Germany.1252  LC_CTYPE=German_Germany.1252   
[3] LC_MONETARY=German_Germany.1252 LC_NUMERIC=C                   
[5] LC_TIME=German_Germany.1252    `

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] staplr_2.9.0    lattice_0.20-38

loaded via a namespace (and not attached):
[1] compiler_3.6.1   magrittr_1.5     assertthat_0.2.1 tools_3.6.1      stringi_1.4.3   
[6] grid_3.6.1       stringr_1.4.0    packrat_0.5.0    tcltk_3.6.1

`system("java -version")`

java version "12.0.2" 2019-07-16
Java(TM) SE Runtime Environment (build 12.0.2+10)
Java HotSpot(TM) 64-Bit Server VM (build 12.0.2+10, mixed mode, sharing)

**Comment by oganm** [comment]
127 is the output from `system` failing to execute the command. You have the CRAN version of staplr which still uses a pdftk installation from the system. Did you install pdftk prior to using the `staple_pdf` function? If not you need to get pdftk from [here](https://www.pdflabs.com/tools/pdftk-server/) and make sure its on your PATH. Alternatively, you can install the development version here by doing

```r
devtools::install_github('pridiltal/staplr')
```
This version should work without pdftk.

If you have pdftk installed already then we have a different problem

Note to self: Removing pdftk requirement from readme before we push this change to CRAN may have been a little shortsighted.

Note to self 2: Returned values could be more informative even though bulk of the work is side effects.

**Comment by RichardMeyer-Eppler** [comment]
Thanks for the swift response! Indeed, I had not realized that the CRAN release still requires pdftk whereas the github version does not.

Updating to the github version fixed the issue. Looking forward to using your package!
