### ISSUE TITLE
Staplr removed for real this time

### ISSUE THREAD

**Issue by oganm** [pridiltal/staplr#49]
https://cran.r-project.org/web/packages/staplr/index.html

@pridiltal Did you get a notification about this? A `devtools::check` seems to think everything's fine

**Comment by pridiltal** [comment]
@oganm  Could you please check this

You have an unstated and unchecked Java version requirement: see
Writing R Extensions' §1.6.

**Comment by oganm** [comment]
Ah. I assumed we could outsource that to rJava and it'd be fine. will look into it

**Comment by oganm** [comment]
> Make sure that any version requirement for Java code is both declared in the ‘SystemRequirements’ field and tested at runtime

I believe this is the relevant section. I have added java 8 to system requirements and included the recommended check. should be fine now.

**Comment by pridiltal** [comment]
Hi @oganm could you please check this

      The description has
     'staplr' requires a Java installation on your system.

     but as SystemRequirements says, that is not sufficient.  It seems it can
     run some things without Java (none AFAICS without Java >= 8) but almost
     all the examples are in \dontrun.  Either
           - the package should test for Java >=8 in .onLoad, or
           - it should be made clear what parts require Java and what parts do not.

**Comment by oganm** [comment]
on it

**Comment by oganm** [comment]
Description now confirms SystemRequirements and also reads "requires Java 8". I have moved the check for java to onLoad as suggested here since there is only one function that doesn't require java (rename_files) and I suspect it is not what most people use the package for

**Comment by pridiltal** [comment]
Awesome!  The submission team is on vacation from Aug 14, 2020 to Aug 24, 2020. During this time the submission of packages is not possible. I'll submit this on 24th and update you soon.

**Comment by pridiltal** [comment]
Woo hoo ! Our package (version 3.1.0)is back on CRAN ⚓ .
