### ISSUE TITLE
overrwrites does not work if you run this code twice

### ISSUE THREAD

**Issue by msgoussi** [pridiltal/staplr#61]
if (requireNamespace("lattice", quietly = TRUE)) {
  dir <- tempdir()
  for(i in 1:3) {
    pdf(file.path(dir, paste("plot", i, ".pdf", sep = "")))
    print(lattice::xyplot(iris[,1] ~ iris[,i], data = iris))
    dev.off()
  }
  output_file <- file.path(dir, paste('Full_pdf.pdf',  sep = ""))
  staple_pdf(input_directory = dir, output_filepath = output_file)
}

Error: The given output filename: C:\Users\310677\AppData\Local\Temp\Rtmp082zIl\Full_pdf.pdf
   matches an input filename.  Exiting.
Errors encountered.  No output created.
Done.  Input errors, so no output created.
[1] 1

**Comment by oganm** [comment]
Pushed a fix that should let this work.
