### ISSUE TITLE
Warning for pdftk installation

### ISSUE THREAD

**Issue by padpadpadpad** [pridiltal/staplr#7]
The Mac installation of pdftk from their website does not work and has not been updated for a long time (see [this](https://stackoverflow.com/questions/39750883/pdftk-hanging-on-macos-sierra) SO conversation). This causes staple_pdf() to hang infinitely.

In the above conversation they give a useable [link](https://www.pdflabs.com/tools/pdftk-the-pdf-toolkit/pdftk_server-2.02-mac_osx-10.11-setup.pkg) for the installation of pdftk on Mac that might be worth mentioning in the README. Not really your fault at all but nice to mention. Again I could do the PR for this.

After I installed using the download of that link it worked fine on MacOS High Sierra 10.13.4.

Cheers
Dan

**Comment by pridiltal** [comment]
Thank you very much. This is very important. Feel free to make a PR.
